# save path: /home/zerone/.config/pipewire/client.conf.d/10-lowlatency.conf
# save path: /home/zerone/.config/pipewire/client-rt.conf.d/10-lowlatency.conf
context.properties = {
    default.clock.quantum       = 512
    default.clock.min-quantum   = 32
    default.clock.max-quantum   = 1024
    default.clock.quantum-limit = 1024
}
