# save path: /home/zerone/.config/pipewire/pipewire.conf.d/bluetooth-lowlatency.conf
context.properties = {
    # Bluetooth needs a little headroom on the CSR clone adapter.
    default.clock.quantum = 512
    default.clock.min-quantum = 256
    default.clock.max-quantum = 1024
    default.clock.quantum-limit = 1024
    default.clock.allow-resampling = true
    default.clock.rate = 48000
    default.clock.allowed-rates = [ 48000 ]
}
