config_version = 14

[audio]
enable_sounds = true

[backdrop]
blur_intensity = 0.0
tint_intensity = 0.0

[bar.default]
background_opacity = 0.9499999787658453
border = "primary"
capsule_fill = "hover"
capsule_foreground = "primary"
capsule_thickness = 0.99999998137354851
center = [ "clock", "calendar" ]
color = "primary"
end = [ "tray", "notifications", "clipboard", "bluetooth", "cpu", "ram", "sysmon_2", "volume", "control-center", "session" ]
font_family = "Monofur Nerd Font Mono"
font_weight = 300
icon_color = "secondary"
margin_edge = 6
margin_ends = 1030
padding = 15
panel_overlap = 2
radius = 9
scale = 0.90000000596046448
start = [ "wallpaper", "wallhaven", "todo", "workspaces", "network_rx", "network_tx" ]
thickness = 30
widget_spacing = 10

    [bar.default.dead_zone.actions]
    scroll_down = "volume-down 1"
    scroll_up = "volume-up 1"

[calendar]

[control_center]
compact = false
hidden_tabs = [ "media", "monitor", "power", "screen-time" ]
sidebar = "full"
sidebar_section = "full"
width = 600

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "clipboard"

    [[control_center.shortcuts]]
    type = "wallpaper"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 1008.0
    box_width = 1136.0
    cx = 1208.0
    cy = 680.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        background_opacity = 0.0
        background_padding = 0
        background_radius = 14
        bar_width = 0.5
        bloom_intensity = 0.55000000000000004
        inner_diameter = 0.65000000000000002
        ring_opacity = 0.60000000000000009
        rotation_speed = 1.3
        sensitivity = 2.5
        visualization_mode = "bars_rings"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 320.0
    box_width = 416.0
    cx = 2272.0
    cy = 272.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = true
        background_color = "outline"
        background_opacity = 1.0
        background_padding = 12
        background_radius = 25
        color = "secondary"
        forecast_days = 6
        shadow = false
        show_forecast = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 2199.0
    cy = 803.5
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "noctalia/ccal:calendar_desktop"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = true
        background_color = "outline"
        background_opacity = 1.0
        background_padding = 18.0
        background_radius = 25

[dock]
active_scale = 1.3000000193715096
background_opacity = 0.40999999083578587
cross_axis_padding = 6
icon_size = 34
inactive_opacity = 0.69999998435378075
inactive_scale = 0.80000001192092896
item_spacing = 2
magnification_scale = 1.4000000059604645
main_axis_padding = 10
margin_edge = 8
shadow = false
show_dots = true

[hooks]
wallpaper_changed = "python3 /home/zerone/.config/kitty/run_reload_all.py"

[hot_corners]
delay_ms = 300
enabled = true

    [hot_corners.top_right]
    action = "command"
    command = "noctalia msg session lock"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 30

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 1800.0

[location]
address = "GuangZhou"

[lockscreen]
blur_intensity = 0.58999998681247234
blurred_desktop = true
tint_intensity = 0.69999998435378075

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-widget-0000000000000002", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 150.0
    box_width = 810.0
    cx = 1224.0
    cy = 1106.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "secondary"
        background_opacity = 0.0
        background_radius = 12.0
        center_password_text = false
        input_opacity = 0.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = true
        show_session_buttons = false
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 320.0
    box_width = 496.0
    cx = 1200.0
    cy = 480.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 0.0
        center_text = true
        clock_style = "digital"
        color = "primary"
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 512.0
    box_width = 496.0
    cx = 2288.0
    cy = 304.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background_opacity = 0.0
        color = "primary"
        forecast_days = 6
        show_forecast = true

[notification]
background_opacity = 0.99999997764825821
border = false
position = "top_center"
scale = 0.85000000521540642

[osd]
background_opacity = 0.99999997764825821
border = false
offset_y = 6

[plugin_settings."h-jangra/keyviz"]
overlay_position = "bottom_left"
padding = 8

[plugin_settings."noctalia/ccal"]
events = [ "L 06-05 妈", "L 09-24 Dear", "L 10-30 恬", "L 04-12 爸" ]
refresh_interval = 2512

[plugin_settings."noctalia/screen_recorder"]
directory = ""

[plugin_settings."noctalia/wallhaven"]
download_dir = ""

[plugins]
auto_update = "all"
enabled = [
    "noctalia/translator",
    "noctalia/wallhaven",
    "nightwatch75/todo",
    "noctalia/ccal",
    "zerone/system-monitor",
    "h-jangra/keyviz"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "/home/zerone/.config/noctalia/plugins/"
    name = "ccal"

[shell]
app_icon_color = "secondary"
app_icon_colorize = true
button_borders = false
card_borders = false
clipboard_history_max_entries = 500
corner_radius_scale = 2.0
font_family = "Monofur Nerd Font Mono"
input_borders = false
panel_anchor_bar = "default"
polkit_agent = true
popup_borders = false
settings_show_advanced = true
telemetry_enabled = false
time_format = "{:%H:%M:%S}"

    [shell.animation]
    speed = 0.40000000596046448

    [shell.launcher]
    session_search = true
    show_app_actions = true

        [shell.launcher.providers.wallpaper]
        prefix = ""

    [shell.panel]
    borders = false
    launcher_session_search = true
    session_placement = "centered"
    shadow = false
    transparency_mode = "glass"
    wallpaper_placement = "centered"

    [shell.screen_corners]
    enabled = true
    size = 25

    [shell.screenshot]
    confirm_region = true

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.79999998211860657
    blur = 71
    direction = "center"

[theme]
builtin = "Rosé Pine"
community_palette = "Everforest Material"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "ghostty", "kcolorscheme", "kitty", "niri", "qt" ]
    community_ids = [ "claude-code", "codex", "opencode", "pi-agent", "discord", "telegram", "fastfetch", "obs", "zathura", "bat" ]

[wallpaper]
directory = "/home/zerone/Pictures/Wallpapers"
edge_smoothness = 0.39999999105930328
fill_color = "primary"
transition_duration = 4000
transition_on_startup = true

    [wallpaper.automation]
    enabled = true
    order = "alphabetical"

    [wallpaper.default]
    path = "/home/zerone/Pictures/Wallpapers/0482.jpg"

    [wallpaper.last]
    path = "/home/zerone/Pictures/Wallpapers/0482.jpg"

    [wallpaper.monitor.DP-1]
    fill_color = "primary"

    [wallpaper.monitors.DP-1]
    path = "/home/zerone/Pictures/Wallpapers/0482.jpg"

[widget.bluetooth]
enabled = false

[widget.calendar]
font_family = "AaNLYDSYY (Non-Commercial Use)"
scale = 0.90000000000000013
type = "noctalia/ccal:calendar"

[widget.clipboard]
enabled = false

[widget.clock]
color = "tertiary"
font_weight = 700
format = "{:%H:%M:%S}"

[widget.control-center]
enabled = false

[widget.cpu]
enabled = false

[widget.network_rx]
network_speed_compact = true
scale = 0.90000000000000013

[widget.network_tx]
network_speed_compact = true
scale = 0.90000000000000013

[widget.notifications]
enabled = false

[widget.ram]
enabled = false
stat = "ram_pct"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.session]
enabled = false

[widget.sysmon_2]
color = "primary"
icon_color = "secondary"
type = "zerone/system-monitor:sysmon"

[widget.todo]
color = "secondary"
enabled = false
type = "nightwatch75/todo:todo"

[widget.tray]
color = "primary"
drawer = true
drawer_columns = 4
drawer_item_size = 14.0
hidden = [ "udiskie" ]
icon_color = "secondary"
pinned = [ "wechat" ]
scale = 0.85000000000000009

[widget.volume]
enabled = false

[widget.wallhaven]
enabled = false
type = "noctalia/wallhaven:wallhaven"

[widget.wallpaper]
enabled = false

[widget.workspaces]
enabled = false
hide_when_empty = true
